// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sentinel/provider/v2/params.proto

package sentinel.provider.v2;

public final class ParamsOuterClass {
  private ParamsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentinel.provider.v2.Params)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the deposit field is set.
     */
    boolean hasDeposit();
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
     * @return The deposit.
     */
    cosmos.base.v1beta1.CoinOuterClass.Coin getDeposit();
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getDepositOrBuilder();

    /**
     * <code>string staking_share = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     * @return The stakingShare.
     */
    java.lang.String getStakingShare();
    /**
     * <code>string staking_share = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     * @return The bytes for stakingShare.
     */
    com.google.protobuf.ByteString
        getStakingShareBytes();
  }
  /**
   * Protobuf type {@code sentinel.provider.v2.Params}
   */
  public static final class Params extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentinel.provider.v2.Params)
      ParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Params.newBuilder() to construct.
    private Params(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Params() {
      stakingShare_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Params();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.provider.v2.ParamsOuterClass.internal_static_sentinel_provider_v2_Params_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.provider.v2.ParamsOuterClass.internal_static_sentinel_provider_v2_Params_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.provider.v2.ParamsOuterClass.Params.class, sentinel.provider.v2.ParamsOuterClass.Params.Builder.class);
    }

    private int bitField0_;
    public static final int DEPOSIT_FIELD_NUMBER = 1;
    private cosmos.base.v1beta1.CoinOuterClass.Coin deposit_;
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the deposit field is set.
     */
    @java.lang.Override
    public boolean hasDeposit() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
     * @return The deposit.
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.Coin getDeposit() {
      return deposit_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : deposit_;
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getDepositOrBuilder() {
      return deposit_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : deposit_;
    }

    public static final int STAKING_SHARE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stakingShare_ = "";
    /**
     * <code>string staking_share = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     * @return The stakingShare.
     */
    @java.lang.Override
    public java.lang.String getStakingShare() {
      java.lang.Object ref = stakingShare_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stakingShare_ = s;
        return s;
      }
    }
    /**
     * <code>string staking_share = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
     * @return The bytes for stakingShare.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStakingShareBytes() {
      java.lang.Object ref = stakingShare_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stakingShare_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getDeposit());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stakingShare_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stakingShare_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDeposit());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stakingShare_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stakingShare_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentinel.provider.v2.ParamsOuterClass.Params)) {
        return super.equals(obj);
      }
      sentinel.provider.v2.ParamsOuterClass.Params other = (sentinel.provider.v2.ParamsOuterClass.Params) obj;

      if (hasDeposit() != other.hasDeposit()) return false;
      if (hasDeposit()) {
        if (!getDeposit()
            .equals(other.getDeposit())) return false;
      }
      if (!getStakingShare()
          .equals(other.getStakingShare())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDeposit()) {
        hash = (37 * hash) + DEPOSIT_FIELD_NUMBER;
        hash = (53 * hash) + getDeposit().hashCode();
      }
      hash = (37 * hash) + STAKING_SHARE_FIELD_NUMBER;
      hash = (53 * hash) + getStakingShare().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sentinel.provider.v2.ParamsOuterClass.Params parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sentinel.provider.v2.ParamsOuterClass.Params parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.provider.v2.ParamsOuterClass.Params parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentinel.provider.v2.ParamsOuterClass.Params prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentinel.provider.v2.Params}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentinel.provider.v2.Params)
        sentinel.provider.v2.ParamsOuterClass.ParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentinel.provider.v2.ParamsOuterClass.internal_static_sentinel_provider_v2_Params_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentinel.provider.v2.ParamsOuterClass.internal_static_sentinel_provider_v2_Params_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentinel.provider.v2.ParamsOuterClass.Params.class, sentinel.provider.v2.ParamsOuterClass.Params.Builder.class);
      }

      // Construct using sentinel.provider.v2.ParamsOuterClass.Params.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDepositFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        deposit_ = null;
        if (depositBuilder_ != null) {
          depositBuilder_.dispose();
          depositBuilder_ = null;
        }
        stakingShare_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentinel.provider.v2.ParamsOuterClass.internal_static_sentinel_provider_v2_Params_descriptor;
      }

      @java.lang.Override
      public sentinel.provider.v2.ParamsOuterClass.Params getDefaultInstanceForType() {
        return sentinel.provider.v2.ParamsOuterClass.Params.getDefaultInstance();
      }

      @java.lang.Override
      public sentinel.provider.v2.ParamsOuterClass.Params build() {
        sentinel.provider.v2.ParamsOuterClass.Params result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentinel.provider.v2.ParamsOuterClass.Params buildPartial() {
        sentinel.provider.v2.ParamsOuterClass.Params result = new sentinel.provider.v2.ParamsOuterClass.Params(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sentinel.provider.v2.ParamsOuterClass.Params result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.deposit_ = depositBuilder_ == null
              ? deposit_
              : depositBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stakingShare_ = stakingShare_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentinel.provider.v2.ParamsOuterClass.Params) {
          return mergeFrom((sentinel.provider.v2.ParamsOuterClass.Params)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentinel.provider.v2.ParamsOuterClass.Params other) {
        if (other == sentinel.provider.v2.ParamsOuterClass.Params.getDefaultInstance()) return this;
        if (other.hasDeposit()) {
          mergeDeposit(other.getDeposit());
        }
        if (!other.getStakingShare().isEmpty()) {
          stakingShare_ = other.stakingShare_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getDepositFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                stakingShare_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private cosmos.base.v1beta1.CoinOuterClass.Coin deposit_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> depositBuilder_;
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
       * @return Whether the deposit field is set.
       */
      public boolean hasDeposit() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
       * @return The deposit.
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin getDeposit() {
        if (depositBuilder_ == null) {
          return deposit_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : deposit_;
        } else {
          return depositBuilder_.getMessage();
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setDeposit(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (depositBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deposit_ = value;
        } else {
          depositBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setDeposit(
          cosmos.base.v1beta1.CoinOuterClass.Coin.Builder builderForValue) {
        if (depositBuilder_ == null) {
          deposit_ = builderForValue.build();
        } else {
          depositBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeDeposit(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (depositBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            deposit_ != null &&
            deposit_ != cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance()) {
            getDepositBuilder().mergeFrom(value);
          } else {
            deposit_ = value;
          }
        } else {
          depositBuilder_.mergeFrom(value);
        }
        if (deposit_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearDeposit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deposit_ = null;
        if (depositBuilder_ != null) {
          depositBuilder_.dispose();
          depositBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin.Builder getDepositBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDepositFieldBuilder().getBuilder();
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getDepositOrBuilder() {
        if (depositBuilder_ != null) {
          return depositBuilder_.getMessageOrBuilder();
        } else {
          return deposit_ == null ?
              cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : deposit_;
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 1 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> 
          getDepositFieldBuilder() {
        if (depositBuilder_ == null) {
          depositBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder>(
                  getDeposit(),
                  getParentForChildren(),
                  isClean());
          deposit_ = null;
        }
        return depositBuilder_;
      }

      private java.lang.Object stakingShare_ = "";
      /**
       * <code>string staking_share = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
       * @return The stakingShare.
       */
      public java.lang.String getStakingShare() {
        java.lang.Object ref = stakingShare_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stakingShare_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string staking_share = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
       * @return The bytes for stakingShare.
       */
      public com.google.protobuf.ByteString
          getStakingShareBytes() {
        java.lang.Object ref = stakingShare_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stakingShare_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string staking_share = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
       * @param value The stakingShare to set.
       * @return This builder for chaining.
       */
      public Builder setStakingShare(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stakingShare_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string staking_share = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStakingShare() {
        stakingShare_ = getDefaultInstance().getStakingShare();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string staking_share = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec"];</code>
       * @param value The bytes for stakingShare to set.
       * @return This builder for chaining.
       */
      public Builder setStakingShareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stakingShare_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentinel.provider.v2.Params)
    }

    // @@protoc_insertion_point(class_scope:sentinel.provider.v2.Params)
    private static final sentinel.provider.v2.ParamsOuterClass.Params DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentinel.provider.v2.ParamsOuterClass.Params();
    }

    public static sentinel.provider.v2.ParamsOuterClass.Params getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Params>
        PARSER = new com.google.protobuf.AbstractParser<Params>() {
      @java.lang.Override
      public Params parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Params> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Params> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentinel.provider.v2.ParamsOuterClass.Params getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_provider_v2_Params_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentinel_provider_v2_Params_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!sentinel/provider/v2/params.proto\022\024sen" +
      "tinel.provider.v2\032\024gogoproto/gogo.proto\032" +
      "\036cosmos/base/v1beta1/coin.proto\"\201\001\n\006Para" +
      "ms\0220\n\007deposit\030\001 \001(\0132\031.cosmos.base.v1beta" +
      "1.CoinB\004\310\336\037\000\022E\n\rstaking_share\030\002 \001(\tB.\310\336\037" +
      "\000\332\336\037&github.com/cosmos/cosmos-sdk/types." +
      "DecB;Z1github.com/sentinel-official/hub/" +
      "x/provider/types\310\341\036\000\250\342\036\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf2.GoGoProtos.getDescriptor(),
          cosmos.base.v1beta1.CoinOuterClass.getDescriptor(),
        });
    internal_static_sentinel_provider_v2_Params_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sentinel_provider_v2_Params_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentinel_provider_v2_Params_descriptor,
        new java.lang.String[] { "Deposit", "StakingShare", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf2.GoGoProtos.customtype);
    registry.add(com.google.protobuf2.GoGoProtos.equalAll);
    registry.add(com.google.protobuf2.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf2.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf2.GoGoProtos.getDescriptor();
    cosmos.base.v1beta1.CoinOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
