// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sentinel/subscription/v1/subscription.proto

package sentinel.subscription.v1;

public final class SubscriptionOuterClass {
  private SubscriptionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentinel.subscription.v1.Subscription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string owner = 2;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 2;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>string node = 3;</code>
     * @return The node.
     */
    java.lang.String getNode();
    /**
     * <code>string node = 3;</code>
     * @return The bytes for node.
     */
    com.google.protobuf.ByteString
        getNodeBytes();

    /**
     * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
     * @return Whether the price field is set.
     */
    boolean hasPrice();
    /**
     * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
     * @return The price.
     */
    cosmos.base.v1beta1.CoinOuterClass.Coin getPrice();
    /**
     * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getPriceOrBuilder();

    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
     * @return Whether the deposit field is set.
     */
    boolean hasDeposit();
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
     * @return The deposit.
     */
    cosmos.base.v1beta1.CoinOuterClass.Coin getDeposit();
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getDepositOrBuilder();

    /**
     * <code>uint64 plan = 6;</code>
     * @return The plan.
     */
    long getPlan();

    /**
     * <code>string denom = 7;</code>
     * @return The denom.
     */
    java.lang.String getDenom();
    /**
     * <code>string denom = 7;</code>
     * @return The bytes for denom.
     */
    com.google.protobuf.ByteString
        getDenomBytes();

    /**
     * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return Whether the expiry field is set.
     */
    boolean hasExpiry();
    /**
     * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return The expiry.
     */
    com.google.protobuf.Timestamp getExpiry();
    /**
     * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    com.google.protobuf.TimestampOrBuilder getExpiryOrBuilder();

    /**
     * <code>string free = 9 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     * @return The free.
     */
    java.lang.String getFree();
    /**
     * <code>string free = 9 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     * @return The bytes for free.
     */
    com.google.protobuf.ByteString
        getFreeBytes();

    /**
     * <code>.sentinel.types.v1.Status status = 10;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.sentinel.types.v1.Status status = 10;</code>
     * @return The status.
     */
    sentinel.types.v1.StatusOuterClass.Status getStatus();

    /**
     * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return Whether the statusAt field is set.
     */
    boolean hasStatusAt();
    /**
     * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return The statusAt.
     */
    com.google.protobuf.Timestamp getStatusAt();
    /**
     * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    com.google.protobuf.TimestampOrBuilder getStatusAtOrBuilder();
  }
  /**
   * Protobuf type {@code sentinel.subscription.v1.Subscription}
   */
  public static final class Subscription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentinel.subscription.v1.Subscription)
      SubscriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Subscription.newBuilder() to construct.
    private Subscription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subscription() {
      owner_ = "";
      node_ = "";
      denom_ = "";
      free_ = "";
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Subscription();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.subscription.v1.SubscriptionOuterClass.internal_static_sentinel_subscription_v1_Subscription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.subscription.v1.SubscriptionOuterClass.internal_static_sentinel_subscription_v1_Subscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.subscription.v1.SubscriptionOuterClass.Subscription.class, sentinel.subscription.v1.SubscriptionOuterClass.Subscription.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int OWNER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object owner_ = "";
    /**
     * <code>string owner = 2;</code>
     * @return The owner.
     */
    @java.lang.Override
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 2;</code>
     * @return The bytes for owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object node_ = "";
    /**
     * <code>string node = 3;</code>
     * @return The node.
     */
    @java.lang.Override
    public java.lang.String getNode() {
      java.lang.Object ref = node_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        node_ = s;
        return s;
      }
    }
    /**
     * <code>string node = 3;</code>
     * @return The bytes for node.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeBytes() {
      java.lang.Object ref = node_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        node_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private cosmos.base.v1beta1.CoinOuterClass.Coin price_;
    /**
     * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
     * @return Whether the price field is set.
     */
    @java.lang.Override
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
     * @return The price.
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.Coin getPrice() {
      return price_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : price_;
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getPriceOrBuilder() {
      return price_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : price_;
    }

    public static final int DEPOSIT_FIELD_NUMBER = 5;
    private cosmos.base.v1beta1.CoinOuterClass.Coin deposit_;
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
     * @return Whether the deposit field is set.
     */
    @java.lang.Override
    public boolean hasDeposit() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
     * @return The deposit.
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.Coin getDeposit() {
      return deposit_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : deposit_;
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getDepositOrBuilder() {
      return deposit_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : deposit_;
    }

    public static final int PLAN_FIELD_NUMBER = 6;
    private long plan_ = 0L;
    /**
     * <code>uint64 plan = 6;</code>
     * @return The plan.
     */
    @java.lang.Override
    public long getPlan() {
      return plan_;
    }

    public static final int DENOM_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object denom_ = "";
    /**
     * <code>string denom = 7;</code>
     * @return The denom.
     */
    @java.lang.Override
    public java.lang.String getDenom() {
      java.lang.Object ref = denom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        denom_ = s;
        return s;
      }
    }
    /**
     * <code>string denom = 7;</code>
     * @return The bytes for denom.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDenomBytes() {
      java.lang.Object ref = denom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        denom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRY_FIELD_NUMBER = 8;
    private com.google.protobuf.Timestamp expiry_;
    /**
     * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return Whether the expiry field is set.
     */
    @java.lang.Override
    public boolean hasExpiry() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return The expiry.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getExpiry() {
      return expiry_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiry_;
    }
    /**
     * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getExpiryOrBuilder() {
      return expiry_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiry_;
    }

    public static final int FREE_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object free_ = "";
    /**
     * <code>string free = 9 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     * @return The free.
     */
    @java.lang.Override
    public java.lang.String getFree() {
      java.lang.Object ref = free_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        free_ = s;
        return s;
      }
    }
    /**
     * <code>string free = 9 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
     * @return The bytes for free.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFreeBytes() {
      java.lang.Object ref = free_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        free_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 10;
    private int status_ = 0;
    /**
     * <code>.sentinel.types.v1.Status status = 10;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.sentinel.types.v1.Status status = 10;</code>
     * @return The status.
     */
    @java.lang.Override public sentinel.types.v1.StatusOuterClass.Status getStatus() {
      sentinel.types.v1.StatusOuterClass.Status result = sentinel.types.v1.StatusOuterClass.Status.forNumber(status_);
      return result == null ? sentinel.types.v1.StatusOuterClass.Status.UNRECOGNIZED : result;
    }

    public static final int STATUS_AT_FIELD_NUMBER = 11;
    private com.google.protobuf.Timestamp statusAt_;
    /**
     * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return Whether the statusAt field is set.
     */
    @java.lang.Override
    public boolean hasStatusAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     * @return The statusAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getStatusAt() {
      return statusAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : statusAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getStatusAtOrBuilder() {
      return statusAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : statusAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(node_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, node_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getPrice());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(5, getDeposit());
      }
      if (plan_ != 0L) {
        output.writeUInt64(6, plan_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(denom_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, denom_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(8, getExpiry());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(free_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, free_);
      }
      if (status_ != sentinel.types.v1.StatusOuterClass.Status.STATUS_UNSPECIFIED.getNumber()) {
        output.writeEnum(10, status_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(11, getStatusAt());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(node_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, node_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPrice());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getDeposit());
      }
      if (plan_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, plan_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(denom_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, denom_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getExpiry());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(free_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, free_);
      }
      if (status_ != sentinel.types.v1.StatusOuterClass.Status.STATUS_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, status_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getStatusAt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentinel.subscription.v1.SubscriptionOuterClass.Subscription)) {
        return super.equals(obj);
      }
      sentinel.subscription.v1.SubscriptionOuterClass.Subscription other = (sentinel.subscription.v1.SubscriptionOuterClass.Subscription) obj;

      if (getId()
          != other.getId()) return false;
      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (!getNode()
          .equals(other.getNode())) return false;
      if (hasPrice() != other.hasPrice()) return false;
      if (hasPrice()) {
        if (!getPrice()
            .equals(other.getPrice())) return false;
      }
      if (hasDeposit() != other.hasDeposit()) return false;
      if (hasDeposit()) {
        if (!getDeposit()
            .equals(other.getDeposit())) return false;
      }
      if (getPlan()
          != other.getPlan()) return false;
      if (!getDenom()
          .equals(other.getDenom())) return false;
      if (hasExpiry() != other.hasExpiry()) return false;
      if (hasExpiry()) {
        if (!getExpiry()
            .equals(other.getExpiry())) return false;
      }
      if (!getFree()
          .equals(other.getFree())) return false;
      if (status_ != other.status_) return false;
      if (hasStatusAt() != other.hasStatusAt()) return false;
      if (hasStatusAt()) {
        if (!getStatusAt()
            .equals(other.getStatusAt())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNode().hashCode();
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + getPrice().hashCode();
      }
      if (hasDeposit()) {
        hash = (37 * hash) + DEPOSIT_FIELD_NUMBER;
        hash = (53 * hash) + getDeposit().hashCode();
      }
      hash = (37 * hash) + PLAN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlan());
      hash = (37 * hash) + DENOM_FIELD_NUMBER;
      hash = (53 * hash) + getDenom().hashCode();
      if (hasExpiry()) {
        hash = (37 * hash) + EXPIRY_FIELD_NUMBER;
        hash = (53 * hash) + getExpiry().hashCode();
      }
      hash = (37 * hash) + FREE_FIELD_NUMBER;
      hash = (53 * hash) + getFree().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      if (hasStatusAt()) {
        hash = (37 * hash) + STATUS_AT_FIELD_NUMBER;
        hash = (53 * hash) + getStatusAt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentinel.subscription.v1.SubscriptionOuterClass.Subscription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentinel.subscription.v1.Subscription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentinel.subscription.v1.Subscription)
        sentinel.subscription.v1.SubscriptionOuterClass.SubscriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentinel.subscription.v1.SubscriptionOuterClass.internal_static_sentinel_subscription_v1_Subscription_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentinel.subscription.v1.SubscriptionOuterClass.internal_static_sentinel_subscription_v1_Subscription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentinel.subscription.v1.SubscriptionOuterClass.Subscription.class, sentinel.subscription.v1.SubscriptionOuterClass.Subscription.Builder.class);
      }

      // Construct using sentinel.subscription.v1.SubscriptionOuterClass.Subscription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPriceFieldBuilder();
          getDepositFieldBuilder();
          getExpiryFieldBuilder();
          getStatusAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        owner_ = "";
        node_ = "";
        price_ = null;
        if (priceBuilder_ != null) {
          priceBuilder_.dispose();
          priceBuilder_ = null;
        }
        deposit_ = null;
        if (depositBuilder_ != null) {
          depositBuilder_.dispose();
          depositBuilder_ = null;
        }
        plan_ = 0L;
        denom_ = "";
        expiry_ = null;
        if (expiryBuilder_ != null) {
          expiryBuilder_.dispose();
          expiryBuilder_ = null;
        }
        free_ = "";
        status_ = 0;
        statusAt_ = null;
        if (statusAtBuilder_ != null) {
          statusAtBuilder_.dispose();
          statusAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentinel.subscription.v1.SubscriptionOuterClass.internal_static_sentinel_subscription_v1_Subscription_descriptor;
      }

      @java.lang.Override
      public sentinel.subscription.v1.SubscriptionOuterClass.Subscription getDefaultInstanceForType() {
        return sentinel.subscription.v1.SubscriptionOuterClass.Subscription.getDefaultInstance();
      }

      @java.lang.Override
      public sentinel.subscription.v1.SubscriptionOuterClass.Subscription build() {
        sentinel.subscription.v1.SubscriptionOuterClass.Subscription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentinel.subscription.v1.SubscriptionOuterClass.Subscription buildPartial() {
        sentinel.subscription.v1.SubscriptionOuterClass.Subscription result = new sentinel.subscription.v1.SubscriptionOuterClass.Subscription(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sentinel.subscription.v1.SubscriptionOuterClass.Subscription result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.owner_ = owner_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.node_ = node_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.price_ = priceBuilder_ == null
              ? price_
              : priceBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.deposit_ = depositBuilder_ == null
              ? deposit_
              : depositBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.plan_ = plan_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.denom_ = denom_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.expiry_ = expiryBuilder_ == null
              ? expiry_
              : expiryBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.free_ = free_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.statusAt_ = statusAtBuilder_ == null
              ? statusAt_
              : statusAtBuilder_.build();
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentinel.subscription.v1.SubscriptionOuterClass.Subscription) {
          return mergeFrom((sentinel.subscription.v1.SubscriptionOuterClass.Subscription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentinel.subscription.v1.SubscriptionOuterClass.Subscription other) {
        if (other == sentinel.subscription.v1.SubscriptionOuterClass.Subscription.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getNode().isEmpty()) {
          node_ = other.node_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasPrice()) {
          mergePrice(other.getPrice());
        }
        if (other.hasDeposit()) {
          mergeDeposit(other.getDeposit());
        }
        if (other.getPlan() != 0L) {
          setPlan(other.getPlan());
        }
        if (!other.getDenom().isEmpty()) {
          denom_ = other.denom_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.hasExpiry()) {
          mergeExpiry(other.getExpiry());
        }
        if (!other.getFree().isEmpty()) {
          free_ = other.free_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.hasStatusAt()) {
          mergeStatusAt(other.getStatusAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                owner_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                node_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getPriceFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getDepositFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                plan_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                denom_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                input.readMessage(
                    getExpiryFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                free_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 80: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 90: {
                input.readMessage(
                    getStatusAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>uint64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>uint64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 2;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 2;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 2;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        owner_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        owner_ = getDefaultInstance().getOwner();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 2;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        owner_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object node_ = "";
      /**
       * <code>string node = 3;</code>
       * @return The node.
       */
      public java.lang.String getNode() {
        java.lang.Object ref = node_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          node_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string node = 3;</code>
       * @return The bytes for node.
       */
      public com.google.protobuf.ByteString
          getNodeBytes() {
        java.lang.Object ref = node_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          node_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string node = 3;</code>
       * @param value The node to set.
       * @return This builder for chaining.
       */
      public Builder setNode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        node_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string node = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNode() {
        node_ = getDefaultInstance().getNode();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string node = 3;</code>
       * @param value The bytes for node to set.
       * @return This builder for chaining.
       */
      public Builder setNodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        node_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private cosmos.base.v1beta1.CoinOuterClass.Coin price_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> priceBuilder_;
      /**
       * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
       * @return Whether the price field is set.
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
       * @return The price.
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin getPrice() {
        if (priceBuilder_ == null) {
          return price_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : price_;
        } else {
          return priceBuilder_.getMessage();
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setPrice(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (priceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          price_ = value;
        } else {
          priceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setPrice(
          cosmos.base.v1beta1.CoinOuterClass.Coin.Builder builderForValue) {
        if (priceBuilder_ == null) {
          price_ = builderForValue.build();
        } else {
          priceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergePrice(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (priceBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            price_ != null &&
            price_ != cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance()) {
            getPriceBuilder().mergeFrom(value);
          } else {
            price_ = value;
          }
        } else {
          priceBuilder_.mergeFrom(value);
        }
        if (price_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        price_ = null;
        if (priceBuilder_ != null) {
          priceBuilder_.dispose();
          priceBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin.Builder getPriceBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getPriceFieldBuilder().getBuilder();
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getPriceOrBuilder() {
        if (priceBuilder_ != null) {
          return priceBuilder_.getMessageOrBuilder();
        } else {
          return price_ == null ?
              cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : price_;
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin price = 4 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> 
          getPriceFieldBuilder() {
        if (priceBuilder_ == null) {
          priceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder>(
                  getPrice(),
                  getParentForChildren(),
                  isClean());
          price_ = null;
        }
        return priceBuilder_;
      }

      private cosmos.base.v1beta1.CoinOuterClass.Coin deposit_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> depositBuilder_;
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
       * @return Whether the deposit field is set.
       */
      public boolean hasDeposit() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
       * @return The deposit.
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin getDeposit() {
        if (depositBuilder_ == null) {
          return deposit_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : deposit_;
        } else {
          return depositBuilder_.getMessage();
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setDeposit(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (depositBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deposit_ = value;
        } else {
          depositBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setDeposit(
          cosmos.base.v1beta1.CoinOuterClass.Coin.Builder builderForValue) {
        if (depositBuilder_ == null) {
          deposit_ = builderForValue.build();
        } else {
          depositBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeDeposit(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (depositBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            deposit_ != null &&
            deposit_ != cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance()) {
            getDepositBuilder().mergeFrom(value);
          } else {
            deposit_ = value;
          }
        } else {
          depositBuilder_.mergeFrom(value);
        }
        if (deposit_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearDeposit() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deposit_ = null;
        if (depositBuilder_ != null) {
          depositBuilder_.dispose();
          depositBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin.Builder getDepositBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getDepositFieldBuilder().getBuilder();
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getDepositOrBuilder() {
        if (depositBuilder_ != null) {
          return depositBuilder_.getMessageOrBuilder();
        } else {
          return deposit_ == null ?
              cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : deposit_;
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin deposit = 5 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> 
          getDepositFieldBuilder() {
        if (depositBuilder_ == null) {
          depositBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder>(
                  getDeposit(),
                  getParentForChildren(),
                  isClean());
          deposit_ = null;
        }
        return depositBuilder_;
      }

      private long plan_ ;
      /**
       * <code>uint64 plan = 6;</code>
       * @return The plan.
       */
      @java.lang.Override
      public long getPlan() {
        return plan_;
      }
      /**
       * <code>uint64 plan = 6;</code>
       * @param value The plan to set.
       * @return This builder for chaining.
       */
      public Builder setPlan(long value) {

        plan_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 plan = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlan() {
        bitField0_ = (bitField0_ & ~0x00000020);
        plan_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object denom_ = "";
      /**
       * <code>string denom = 7;</code>
       * @return The denom.
       */
      public java.lang.String getDenom() {
        java.lang.Object ref = denom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          denom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string denom = 7;</code>
       * @return The bytes for denom.
       */
      public com.google.protobuf.ByteString
          getDenomBytes() {
        java.lang.Object ref = denom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          denom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string denom = 7;</code>
       * @param value The denom to set.
       * @return This builder for chaining.
       */
      public Builder setDenom(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        denom_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string denom = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDenom() {
        denom_ = getDefaultInstance().getDenom();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string denom = 7;</code>
       * @param value The bytes for denom to set.
       * @return This builder for chaining.
       */
      public Builder setDenomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        denom_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp expiry_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiryBuilder_;
      /**
       * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       * @return Whether the expiry field is set.
       */
      public boolean hasExpiry() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       * @return The expiry.
       */
      public com.google.protobuf.Timestamp getExpiry() {
        if (expiryBuilder_ == null) {
          return expiry_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiry_;
        } else {
          return expiryBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder setExpiry(com.google.protobuf.Timestamp value) {
        if (expiryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          expiry_ = value;
        } else {
          expiryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder setExpiry(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (expiryBuilder_ == null) {
          expiry_ = builderForValue.build();
        } else {
          expiryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder mergeExpiry(com.google.protobuf.Timestamp value) {
        if (expiryBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0) &&
            expiry_ != null &&
            expiry_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getExpiryBuilder().mergeFrom(value);
          } else {
            expiry_ = value;
          }
        } else {
          expiryBuilder_.mergeFrom(value);
        }
        if (expiry_ != null) {
          bitField0_ |= 0x00000080;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder clearExpiry() {
        bitField0_ = (bitField0_ & ~0x00000080);
        expiry_ = null;
        if (expiryBuilder_ != null) {
          expiryBuilder_.dispose();
          expiryBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public com.google.protobuf.Timestamp.Builder getExpiryBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getExpiryFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getExpiryOrBuilder() {
        if (expiryBuilder_ != null) {
          return expiryBuilder_.getMessageOrBuilder();
        } else {
          return expiry_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : expiry_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp expiry = 8 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getExpiryFieldBuilder() {
        if (expiryBuilder_ == null) {
          expiryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getExpiry(),
                  getParentForChildren(),
                  isClean());
          expiry_ = null;
        }
        return expiryBuilder_;
      }

      private java.lang.Object free_ = "";
      /**
       * <code>string free = 9 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @return The free.
       */
      public java.lang.String getFree() {
        java.lang.Object ref = free_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          free_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string free = 9 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @return The bytes for free.
       */
      public com.google.protobuf.ByteString
          getFreeBytes() {
        java.lang.Object ref = free_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          free_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string free = 9 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @param value The free to set.
       * @return This builder for chaining.
       */
      public Builder setFree(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        free_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string free = 9 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFree() {
        free_ = getDefaultInstance().getFree();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string free = 9 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];</code>
       * @param value The bytes for free to set.
       * @return This builder for chaining.
       */
      public Builder setFreeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        free_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.sentinel.types.v1.Status status = 10;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.sentinel.types.v1.Status status = 10;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>.sentinel.types.v1.Status status = 10;</code>
       * @return The status.
       */
      @java.lang.Override
      public sentinel.types.v1.StatusOuterClass.Status getStatus() {
        sentinel.types.v1.StatusOuterClass.Status result = sentinel.types.v1.StatusOuterClass.Status.forNumber(status_);
        return result == null ? sentinel.types.v1.StatusOuterClass.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.sentinel.types.v1.Status status = 10;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(sentinel.types.v1.StatusOuterClass.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000200;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.sentinel.types.v1.Status status = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000200);
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp statusAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> statusAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       * @return Whether the statusAt field is set.
       */
      public boolean hasStatusAt() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       * @return The statusAt.
       */
      public com.google.protobuf.Timestamp getStatusAt() {
        if (statusAtBuilder_ == null) {
          return statusAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : statusAt_;
        } else {
          return statusAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder setStatusAt(com.google.protobuf.Timestamp value) {
        if (statusAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          statusAt_ = value;
        } else {
          statusAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder setStatusAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (statusAtBuilder_ == null) {
          statusAt_ = builderForValue.build();
        } else {
          statusAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder mergeStatusAt(com.google.protobuf.Timestamp value) {
        if (statusAtBuilder_ == null) {
          if (((bitField0_ & 0x00000400) != 0) &&
            statusAt_ != null &&
            statusAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getStatusAtBuilder().mergeFrom(value);
          } else {
            statusAt_ = value;
          }
        } else {
          statusAtBuilder_.mergeFrom(value);
        }
        if (statusAt_ != null) {
          bitField0_ |= 0x00000400;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public Builder clearStatusAt() {
        bitField0_ = (bitField0_ & ~0x00000400);
        statusAt_ = null;
        if (statusAtBuilder_ != null) {
          statusAtBuilder_.dispose();
          statusAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public com.google.protobuf.Timestamp.Builder getStatusAtBuilder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getStatusAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getStatusAtOrBuilder() {
        if (statusAtBuilder_ != null) {
          return statusAtBuilder_.getMessageOrBuilder();
        } else {
          return statusAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : statusAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp status_at = 11 [(.gogoproto.nullable) = false, (.gogoproto.stdtime) = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getStatusAtFieldBuilder() {
        if (statusAtBuilder_ == null) {
          statusAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getStatusAt(),
                  getParentForChildren(),
                  isClean());
          statusAt_ = null;
        }
        return statusAtBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentinel.subscription.v1.Subscription)
    }

    // @@protoc_insertion_point(class_scope:sentinel.subscription.v1.Subscription)
    private static final sentinel.subscription.v1.SubscriptionOuterClass.Subscription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentinel.subscription.v1.SubscriptionOuterClass.Subscription();
    }

    public static sentinel.subscription.v1.SubscriptionOuterClass.Subscription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscription>
        PARSER = new com.google.protobuf.AbstractParser<Subscription>() {
      @java.lang.Override
      public Subscription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Subscription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscription> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentinel.subscription.v1.SubscriptionOuterClass.Subscription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_subscription_v1_Subscription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentinel_subscription_v1_Subscription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+sentinel/subscription/v1/subscription." +
      "proto\022\030sentinel.subscription.v1\032\036cosmos/" +
      "base/v1beta1/coin.proto\032\024gogoproto/gogo." +
      "proto\032\037google/protobuf/timestamp.proto\032\036" +
      "sentinel/types/v1/status.proto\"\216\003\n\014Subsc" +
      "ription\022\n\n\002id\030\001 \001(\004\022\r\n\005owner\030\002 \001(\t\022\014\n\004no" +
      "de\030\003 \001(\t\022.\n\005price\030\004 \001(\0132\031.cosmos.base.v1" +
      "beta1.CoinB\004\310\336\037\000\0220\n\007deposit\030\005 \001(\0132\031.cosm" +
      "os.base.v1beta1.CoinB\004\310\336\037\000\022\014\n\004plan\030\006 \001(\004" +
      "\022\r\n\005denom\030\007 \001(\t\0224\n\006expiry\030\010 \001(\0132\032.google" +
      ".protobuf.TimestampB\010\310\336\037\000\220\337\037\001\022<\n\004free\030\t " +
      "\001(\tB.\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sd" +
      "k/types.Int\022)\n\006status\030\n \001(\0162\031.sentinel.t" +
      "ypes.v1.Status\0227\n\tstatus_at\030\013 \001(\0132\032.goog" +
      "le.protobuf.TimestampB\010\310\336\037\000\220\337\037\001BIZ?githu" +
      "b.com/sentinel-official/hub/x/subscripti" +
      "on/legacy/v1/types\310\341\036\000\250\342\036\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cosmos.base.v1beta1.CoinOuterClass.getDescriptor(),
          com.google.protobuf2.GoGoProtos.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          sentinel.types.v1.StatusOuterClass.getDescriptor(),
        });
    internal_static_sentinel_subscription_v1_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sentinel_subscription_v1_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentinel_subscription_v1_Subscription_descriptor,
        new java.lang.String[] { "Id", "Owner", "Node", "Price", "Deposit", "Plan", "Denom", "Expiry", "Free", "Status", "StatusAt", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf2.GoGoProtos.customtype);
    registry.add(com.google.protobuf2.GoGoProtos.equalAll);
    registry.add(com.google.protobuf2.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf2.GoGoProtos.nullable);
    registry.add(com.google.protobuf2.GoGoProtos.stdtime);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    cosmos.base.v1beta1.CoinOuterClass.getDescriptor();
    com.google.protobuf2.GoGoProtos.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    sentinel.types.v1.StatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
