// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sentinel/node/v2/genesis.proto

package sentinel.node.v2;

public final class Genesis {
  private Genesis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenesisStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentinel.node.v2.GenesisState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<sentinel.node.v2.NodeOuterClass.Node> 
        getNodesList();
    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    sentinel.node.v2.NodeOuterClass.Node getNodes(int index);
    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    int getNodesCount();
    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<? extends sentinel.node.v2.NodeOuterClass.NodeOrBuilder> 
        getNodesOrBuilderList();
    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    sentinel.node.v2.NodeOuterClass.NodeOrBuilder getNodesOrBuilder(
        int index);

    /**
     * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
     * @return Whether the params field is set.
     */
    boolean hasParams();
    /**
     * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
     * @return The params.
     */
    sentinel.node.v2.ParamsOuterClass.Params getParams();
    /**
     * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
     */
    sentinel.node.v2.ParamsOuterClass.ParamsOrBuilder getParamsOrBuilder();
  }
  /**
   * Protobuf type {@code sentinel.node.v2.GenesisState}
   */
  public static final class GenesisState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentinel.node.v2.GenesisState)
      GenesisStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenesisState.newBuilder() to construct.
    private GenesisState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenesisState() {
      nodes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenesisState();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.node.v2.Genesis.internal_static_sentinel_node_v2_GenesisState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.node.v2.Genesis.internal_static_sentinel_node_v2_GenesisState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.node.v2.Genesis.GenesisState.class, sentinel.node.v2.Genesis.GenesisState.Builder.class);
    }

    private int bitField0_;
    public static final int NODES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<sentinel.node.v2.NodeOuterClass.Node> nodes_;
    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public java.util.List<sentinel.node.v2.NodeOuterClass.Node> getNodesList() {
      return nodes_;
    }
    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public java.util.List<? extends sentinel.node.v2.NodeOuterClass.NodeOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public sentinel.node.v2.NodeOuterClass.Node getNodes(int index) {
      return nodes_.get(index);
    }
    /**
     * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public sentinel.node.v2.NodeOuterClass.NodeOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    public static final int PARAMS_FIELD_NUMBER = 2;
    private sentinel.node.v2.ParamsOuterClass.Params params_;
    /**
     * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
     * @return Whether the params field is set.
     */
    @java.lang.Override
    public boolean hasParams() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
     * @return The params.
     */
    @java.lang.Override
    public sentinel.node.v2.ParamsOuterClass.Params getParams() {
      return params_ == null ? sentinel.node.v2.ParamsOuterClass.Params.getDefaultInstance() : params_;
    }
    /**
     * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public sentinel.node.v2.ParamsOuterClass.ParamsOrBuilder getParamsOrBuilder() {
      return params_ == null ? sentinel.node.v2.ParamsOuterClass.Params.getDefaultInstance() : params_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(1, nodes_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getParams());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodes_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getParams());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentinel.node.v2.Genesis.GenesisState)) {
        return super.equals(obj);
      }
      sentinel.node.v2.Genesis.GenesisState other = (sentinel.node.v2.Genesis.GenesisState) obj;

      if (!getNodesList()
          .equals(other.getNodesList())) return false;
      if (hasParams() != other.hasParams()) return false;
      if (hasParams()) {
        if (!getParams()
            .equals(other.getParams())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodesCount() > 0) {
        hash = (37 * hash) + NODES_FIELD_NUMBER;
        hash = (53 * hash) + getNodesList().hashCode();
      }
      if (hasParams()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParams().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentinel.node.v2.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.node.v2.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.node.v2.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.node.v2.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.node.v2.Genesis.GenesisState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.node.v2.Genesis.GenesisState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.node.v2.Genesis.GenesisState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.node.v2.Genesis.GenesisState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static sentinel.node.v2.Genesis.GenesisState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static sentinel.node.v2.Genesis.GenesisState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentinel.node.v2.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.node.v2.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentinel.node.v2.Genesis.GenesisState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentinel.node.v2.GenesisState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentinel.node.v2.GenesisState)
        sentinel.node.v2.Genesis.GenesisStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentinel.node.v2.Genesis.internal_static_sentinel_node_v2_GenesisState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentinel.node.v2.Genesis.internal_static_sentinel_node_v2_GenesisState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentinel.node.v2.Genesis.GenesisState.class, sentinel.node.v2.Genesis.GenesisState.Builder.class);
      }

      // Construct using sentinel.node.v2.Genesis.GenesisState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
          getParamsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
        } else {
          nodes_ = null;
          nodesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        params_ = null;
        if (paramsBuilder_ != null) {
          paramsBuilder_.dispose();
          paramsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentinel.node.v2.Genesis.internal_static_sentinel_node_v2_GenesisState_descriptor;
      }

      @java.lang.Override
      public sentinel.node.v2.Genesis.GenesisState getDefaultInstanceForType() {
        return sentinel.node.v2.Genesis.GenesisState.getDefaultInstance();
      }

      @java.lang.Override
      public sentinel.node.v2.Genesis.GenesisState build() {
        sentinel.node.v2.Genesis.GenesisState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentinel.node.v2.Genesis.GenesisState buildPartial() {
        sentinel.node.v2.Genesis.GenesisState result = new sentinel.node.v2.Genesis.GenesisState(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(sentinel.node.v2.Genesis.GenesisState result) {
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
      }

      private void buildPartial0(sentinel.node.v2.Genesis.GenesisState result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.params_ = paramsBuilder_ == null
              ? params_
              : paramsBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentinel.node.v2.Genesis.GenesisState) {
          return mergeFrom((sentinel.node.v2.Genesis.GenesisState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentinel.node.v2.Genesis.GenesisState other) {
        if (other == sentinel.node.v2.Genesis.GenesisState.getDefaultInstance()) return this;
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        if (other.hasParams()) {
          mergeParams(other.getParams());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                sentinel.node.v2.NodeOuterClass.Node m =
                    input.readMessage(
                        sentinel.node.v2.NodeOuterClass.Node.parser(),
                        extensionRegistry);
                if (nodesBuilder_ == null) {
                  ensureNodesIsMutable();
                  nodes_.add(m);
                } else {
                  nodesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getParamsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<sentinel.node.v2.NodeOuterClass.Node> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          nodes_ = new java.util.ArrayList<sentinel.node.v2.NodeOuterClass.Node>(nodes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          sentinel.node.v2.NodeOuterClass.Node, sentinel.node.v2.NodeOuterClass.Node.Builder, sentinel.node.v2.NodeOuterClass.NodeOrBuilder> nodesBuilder_;

      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<sentinel.node.v2.NodeOuterClass.Node> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public sentinel.node.v2.NodeOuterClass.Node getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setNodes(
          int index, sentinel.node.v2.NodeOuterClass.Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setNodes(
          int index, sentinel.node.v2.NodeOuterClass.Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addNodes(sentinel.node.v2.NodeOuterClass.Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addNodes(
          int index, sentinel.node.v2.NodeOuterClass.Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addNodes(
          sentinel.node.v2.NodeOuterClass.Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addNodes(
          int index, sentinel.node.v2.NodeOuterClass.Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addAllNodes(
          java.lang.Iterable<? extends sentinel.node.v2.NodeOuterClass.Node> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public sentinel.node.v2.NodeOuterClass.Node.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public sentinel.node.v2.NodeOuterClass.NodeOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<? extends sentinel.node.v2.NodeOuterClass.NodeOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public sentinel.node.v2.NodeOuterClass.Node.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            sentinel.node.v2.NodeOuterClass.Node.getDefaultInstance());
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public sentinel.node.v2.NodeOuterClass.Node.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, sentinel.node.v2.NodeOuterClass.Node.getDefaultInstance());
      }
      /**
       * <code>repeated .sentinel.node.v2.Node nodes = 1 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<sentinel.node.v2.NodeOuterClass.Node.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          sentinel.node.v2.NodeOuterClass.Node, sentinel.node.v2.NodeOuterClass.Node.Builder, sentinel.node.v2.NodeOuterClass.NodeOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              sentinel.node.v2.NodeOuterClass.Node, sentinel.node.v2.NodeOuterClass.Node.Builder, sentinel.node.v2.NodeOuterClass.NodeOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }

      private sentinel.node.v2.ParamsOuterClass.Params params_;
      private com.google.protobuf.SingleFieldBuilderV3<
          sentinel.node.v2.ParamsOuterClass.Params, sentinel.node.v2.ParamsOuterClass.Params.Builder, sentinel.node.v2.ParamsOuterClass.ParamsOrBuilder> paramsBuilder_;
      /**
       * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
       * @return Whether the params field is set.
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
       * @return The params.
       */
      public sentinel.node.v2.ParamsOuterClass.Params getParams() {
        if (paramsBuilder_ == null) {
          return params_ == null ? sentinel.node.v2.ParamsOuterClass.Params.getDefaultInstance() : params_;
        } else {
          return paramsBuilder_.getMessage();
        }
      }
      /**
       * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setParams(sentinel.node.v2.ParamsOuterClass.Params value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params_ = value;
        } else {
          paramsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setParams(
          sentinel.node.v2.ParamsOuterClass.Params.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          params_ = builderForValue.build();
        } else {
          paramsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeParams(sentinel.node.v2.ParamsOuterClass.Params value) {
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            params_ != null &&
            params_ != sentinel.node.v2.ParamsOuterClass.Params.getDefaultInstance()) {
            getParamsBuilder().mergeFrom(value);
          } else {
            params_ = value;
          }
        } else {
          paramsBuilder_.mergeFrom(value);
        }
        if (params_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000002);
        params_ = null;
        if (paramsBuilder_ != null) {
          paramsBuilder_.dispose();
          paramsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
       */
      public sentinel.node.v2.ParamsOuterClass.Params.Builder getParamsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getParamsFieldBuilder().getBuilder();
      }
      /**
       * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
       */
      public sentinel.node.v2.ParamsOuterClass.ParamsOrBuilder getParamsOrBuilder() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilder();
        } else {
          return params_ == null ?
              sentinel.node.v2.ParamsOuterClass.Params.getDefaultInstance() : params_;
        }
      }
      /**
       * <code>.sentinel.node.v2.Params params = 2 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          sentinel.node.v2.ParamsOuterClass.Params, sentinel.node.v2.ParamsOuterClass.Params.Builder, sentinel.node.v2.ParamsOuterClass.ParamsOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              sentinel.node.v2.ParamsOuterClass.Params, sentinel.node.v2.ParamsOuterClass.Params.Builder, sentinel.node.v2.ParamsOuterClass.ParamsOrBuilder>(
                  getParams(),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentinel.node.v2.GenesisState)
    }

    // @@protoc_insertion_point(class_scope:sentinel.node.v2.GenesisState)
    private static final sentinel.node.v2.Genesis.GenesisState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentinel.node.v2.Genesis.GenesisState();
    }

    public static sentinel.node.v2.Genesis.GenesisState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenesisState>
        PARSER = new com.google.protobuf.AbstractParser<GenesisState>() {
      @java.lang.Override
      public GenesisState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GenesisState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenesisState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentinel.node.v2.Genesis.GenesisState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_node_v2_GenesisState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentinel_node_v2_GenesisState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036sentinel/node/v2/genesis.proto\022\020sentin" +
      "el.node.v2\032\024gogoproto/gogo.proto\032\033sentin" +
      "el/node/v2/node.proto\032\035sentinel/node/v2/" +
      "params.proto\"k\n\014GenesisState\022+\n\005nodes\030\001 " +
      "\003(\0132\026.sentinel.node.v2.NodeB\004\310\336\037\000\022.\n\006par" +
      "ams\030\002 \001(\0132\030.sentinel.node.v2.ParamsB\004\310\336\037" +
      "\000B7Z-github.com/sentinel-official/hub/x/" +
      "node/types\310\341\036\000\250\342\036\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf2.GoGoProtos.getDescriptor(),
          sentinel.node.v2.NodeOuterClass.getDescriptor(),
          sentinel.node.v2.ParamsOuterClass.getDescriptor(),
        });
    internal_static_sentinel_node_v2_GenesisState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sentinel_node_v2_GenesisState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentinel_node_v2_GenesisState_descriptor,
        new java.lang.String[] { "Nodes", "Params", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf2.GoGoProtos.equalAll);
    registry.add(com.google.protobuf2.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf2.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf2.GoGoProtos.getDescriptor();
    sentinel.node.v2.NodeOuterClass.getDescriptor();
    sentinel.node.v2.ParamsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
